### Create New Question 
POST http://localhost:8080/questions/ HTTP/1.1 
content-type: application/json

{ 
  
    "studentName" : "aishwarya", 
    "question" : "what is machine learning" }

### Get Question by Id 
GET http://localhost:8080/questions/78

### Get all Questions 
GET http://localhost:8080/questions HTTP/1.1

### Create New Answer 
POST http://localhost:8080/questions/answer/83 
content-type: application/json

{
    "answer": "machine learning is jsdkjv"
}

### Update Answer

PUT http://localhost:8080/questions/answer/83 HTTP/1.1 
content-type: application/json

{
    "answer" : "machine learning is something"
}

### Delete Answer By Id 
DELETE http://localhost:8080/questions/answer/110

### Delete Question By Id 
DELETE http://localhost:8080/questions/110

