
### Create New User
POST http://localhost:8080/user/ HTTP/1.1
content-type: application/json

{
    "userName" : "ddd",
    "password" : "123",
    "role" : "admin"
}

### Login
POST http://localhost:8080/user/login HTTP/1.1
content-type: application/json

{
    "userName" : "ccc",
    "password" : "123"
}