
### Create New User
POST http://localhost:8080/user/ HTTP/1.1
content-type: application/json

{
    "userName" : "rohit@123",
    "password" : "Rohit@1234",
    "role" : "admin"
}

### Login
POST http://localhost:8080/user/loginv2 HTTP/1.1
content-type: application/json

{
    "userName" : "rohit",
    "password" : "123"
}
### Book by user id and course id
POST http://localhost:8080/user/1/userEnrollments/16 HTTP/1.1
Content-Type: application/json



### Get all users
GET http://localhost:8080/user/users

### Get all courses
GET http://localhost:8080/user/getuserEnrollments/1

### Get all studentEnrolled
GET http://localhost:8080/user/allStudentEnrolled

### update the user
PUT http://localhost:8080/user/updateUser HTTP/1.1
content-type: application/json

{
  "id" :"62",
  "userName" : "rohitsharma",
  "role" : "admin",
}

### Delete user By Id 
DELETE http://localhost:8080/user/delete/64
