
### Create New User
POST http://localhost:8080/user/ HTTP/1.1
content-type: application/json

{
    "userName" : "hrishikesh",
    "password" : "123",
    "role" : "user"
}

### Login
POST http://localhost:8080/user/login HTTP/1.1
content-type: application/json

{
    "userName" : "hrishikesh",
    "password" : "123"
}